[project]
name = "aeroplane-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "inference-sdk>=0.17.0",
    "opencv-python>=4.11.0.86",
    "setuptools>=75.8.2",
]
